---
title: "Final Project - Report"
author: "Adam Fucich, Asher Andrus, Sophia Baitzel, Anita Avila"
date: "02-29-24"
output:
  prettydoc::html_pretty:
    theme: hpster
    highlight: github
---

## Blood Lead Levels in NYC Children
*Research Question*\
  "How has Blood Lead Level(BLL) changed over time and what areas have higher BLLs?"
      

```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
library(tidyverse)
library(ggrepel)
library(janitor)
#install.packages("devtools")
devtools::install_github("datadotworld/data.world-r", build_vignettes = TRUE)
library(data.world)
Children_Blood_Lead <- download_file_as_data_frame(owner_id = "city-of-ny", dataset_id = "tnry-kwh5", file_name = "children-under-6-yrs-with-elevated-blood-lead-levels-bll-1.csv")
view(Simple_Children_Blood_Lead)
```

## Data Tidying 
```{r, message =FALSE}
Filtered_Children_Blood_Lead <- Children_Blood_Lead %>%
  select(-ends_with("_NOTES")) 

Simple_Children_Blood_Lead <- Filtered_Children_Blood_Lead %>%
  rename(BLL_5 = `Children under 6 years with elevated blood lead levels (BLL) Number BLL >=5 µg/dL`) %>%
  rename(BLL_10 = `Children under 6 years with elevated blood lead levels (BLL) Number BLL>=10 µg/dL`) %>%
  rename(BLL_15 = `Children under 6 years with elevated blood lead levels (BLL) Number BLL>=15 µg/dL`) %>%
  rename(Total_Test = `Children under 6 years with elevated blood lead levels (BLL) Number Tested`) %>%
  rename(BLL_5_ratio = `Children under 6 years with elevated blood lead levels (BLL) Rate  BLL>=5 µg/dL per 1,000 tested`) %>%
  rename(BLL_10_ratio = `Children under 6 years with elevated blood lead levels (BLL) Rate BLL>=10 µg/dL per 1,000 tested`) %>%
  rename(BLL_15_ratio = `Children under 6 years with elevated blood lead levels (BLL) Rate BLL>=15 µg/dL per 1,000 tested`) %>%
  rename(Year = `time_period`)

New_Children_Lead_Poision <- Simple_Children_Blood_Lead %>%
  transform(BLL_5 = as.numeric(BLL_5)) %>%
  transform(BLL_10 = as.numeric(BLL_10)) %>%
  transform(BLL_15 = as.numeric(BLL_15)) %>%
  transform(geo_area_id = as.numeric(geo_area_id)) %>%
  transform(borough_id = as.numeric(borough_id)) %>%
  transform(time_period = as.numeric(time_period)) %>%
  transform(Total_Test = as.numeric(Total_Test)) %>%
  transform(BLL_5_ratio = as.numeric(BLL_5_ratio)) %>%
  transform(BLL_10_ratio = as.numeric(BLL_10_ratio)) %>%
  transform(BLL_15_ratio = as.numeric(BLL_15_ratio))
   
New_Blood_Lead_Children <- New_Children_Lead_Poision %>%
  mutate(Total_Lead_Poisoned = (BLL_5 + BLL_10 + BLL_15)) %>%
  mutate(Total_Not_Lead_Poisioned = (Total_Test) - (BLL_5 + BLL_10 + BLL_15))
```

### Data Viz Area 

```{r fig.width=6, fig.height=6, fig.align='center', echo=FALSE}
view(New_Blood_Lead_Children)


## Line graph comparing total children testing positive for BBL by borough. Needs title?
New_Blood_Lead_Children %>%
  filter(geo_type == "Borough") %>%
  group_by("geo_area_name") %>%
  ggplot() +
  geom_line(aes(x = time_period, y = (Total_Lead_Poisoned / 1000), color = geo_area_name), linewidth = 1.5) +
  scale_x_continuous(name = "Year", breaks = seq(2005, 2016, 1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(name = "Total Cases (thousands)", breaks = seq(0, 17.5, 2.5)) + 
  guides( color = guide_legend(title = "NYC Borough"))
## Do i need to ungroup here?

# Map of the 5 boroughs we could use: https://www.loumovesyou.com/wp-content/uploads/2022/11/FiveBoroughs-01.jpg


## Potentially too many lines, have to think about it for a bit longer
New_Blood_Lead_Children %>%
  filter(geo_type == "Neighborhood (UHF 42)", borough_id == "2") %>%
  group_by(geo_area_name) %>%
  ggplot() +
  geom_line(aes(x = time_period, y = Total_Lead_Poisoned, color = geo_area_name))
  
```


```{r}

```

